# made by: joci12_
# v1.1
options:
    noperm: &cEhhez a parancshoz nincs jogod!
    noplayername: &cAdj meg egy játékosnevet!
    notbanned: &cEz a játékos nincs kitiltva!
    ban: &7[&7&c&lBAN&l&c&7]&7
    kick: &7[&7&c&lKICK&l&c&7]&7
    unban: &7[&7&c&lUNBAN&l&c&7]&7
    warn: &7[&7&c&lWARN&l&c&7]&7
    
command /modera [<text>] [<player>] [<text>]:
  permission: modera.modera
  permission message: {@noperm}

  trigger:
    if arg-1 is "ban":
      execute player command "ban %arg-2%"
      stop

    if arg-1 is "unban":
      execute player command "unban %arg-2%"

    if arg-1 is "kick":
      execute player command "kick %arg-2%"
      stop

    if arg-1 is "warn":
      execute player command "warn %arg-2%"
      stop

    if arg-1 is "silentban":
      execute player command "silentban %arg-2%"
      stop

    if arg-1 is "silentunban":
      execute player command "silentunban %arg-2%"

    if arg-1 is "history":
      execute player command "history %arg-2%"
      stop

    if arg-1 is "clearhistory":
      execute player command "clearhistory %arg-2%"
      stop
      
    if arg-1 is "help":
      send ""
      send "Parancsok:"
      send ""
      send "/ban <játékosnév> <indok> &7[Kitiltja a megadott játékost.]"
      send "/unban <játékosnév> <indok> &7[Feloldja a megadott játékos tiltását.]"
      send "/kick <játékosnév> <indok> &7[Kirúgja a megadott játékost.]"
      send "/warn <játékosnév> <indok> &7[Figyelmezteti a megadott játékost.]"
      send "/silentban <játékosnév> <indok> &7[Jelzés nélkül kitiltja a megadott játékost]"
      send "/silentunban <játékosnév> <indok> &7[Jelzés nélkül feloldja a megadott játékos tiltását]"
      send "/history <játékosnév> &7[Megmutatja a megadott játékos előzményeit.]"
      send "/clearhistory <játékosnév> &7[Törli a megadott játékos előzményeit.]"
      send "/modera update"
      send "/modera help"
      send "/modera version"
      send "/modera"
      stop

    if arg-1 is not set:
      send "    &c&l[modera]"
      send "         V1.1"
      send ""
      send "  Made by: joci12_"
      send "   /modera help"

    if arg-1 is "update":
      send "Frissítések keresése..."
      wait 2 seconds
      send "&aA legújabb &c&l[modera]&l&c &averzió fut a szerveren!"

    if arg-1 is "version":
      send "A jelenlegi &c&l[modera]&l&c &fverzió: &lV1.1"

    if arg-1 is "reload":
      send "&c&l[modera]&l&c &fújratöltése..."
      execute player command "sk reload moderaV1.1.sk"
      send "&c&l[modera]&l&c &aújratöltve!"

command /ban [<player>] [<text>]:
  permission: modera.ban
  permission message: {@noperm}

  trigger:
    if arg-1 is not set:
      send "{@noplayername}"
      stop
      
    if arg-2 is not set:
      add "[%now%] {@ban} &7by &f%player%&7: %arg-2%" to {history::%arg-1%::*}
      execute console command "minecraft:ban %arg-1% &c%player%&c &fkitiltott téged!"
      broadcast "{@ban} &c%player%&c &fkitiltotta &c%arg-1%&c &fjátékost!"
      stop

    execute console command "minecraft:ban %arg-1% &c%player%&c &fkitiltott téged! %newline% &fIndok: &c%arg-2%"
    broadcast "{@ban} &c%player%&c &fkitiltotta &c%arg-1%&c &fjátékost! Indok: &c%arg-2%"
    add "[%now%] {@ban} &7by &f%player%&7: %arg-2%" to {history::%arg-1%::*}

command /unban [<offline player>]:
  permission: modera.unban
  permission message: {@noperm}

  trigger:
    if arg-1 is not set:
      send "{@noplayername}"
      stop

    if arg-1 is banned:
      broadcast "&7[&7&c&lUNBAN&l&c&7]&7 &c%player%&c &ffeloldotta &c%arg-1%&c &ftiltását!"
      execute console command "/minecraft:pardon %arg-1%"

    else:
      send "{@notbanned}"

command /kick [<player>] [<text>]:
  permission: modera.kick
  permission message: {@noperm}

  trigger:
    if arg-1 is not set:
      send "{@noplayername}"
      stop

    if arg-2 is not set:
      add "[%now%] {@kick} &7by &f%player%&7: %arg-2%" to {history::%arg-1%::*}
      broadcast "{@kick} &c%player% &fkirúgta &c%arg-1%&c &fjátékost!"
      execute console command "minecraft:kick %arg-1% &c%player%&c &fkirúgott téged!"
      stop

    execute console command "minecraft:kick %arg-1% &c%player%&c &fkirúgott téged! %newline% &fIndok: &c%arg-2%"
    broadcast "{@kick} &c%player% &fkirúgta &c%arg-1%&c &fjátékost! Indok: &c%arg-2%"
    add "[%now%] {@kick} &7by &f%player%&7: %arg-2%" to {history::%arg-1%::*}
    
command /warn [<player>] [<text>]:
  permission: modera.warn
  permission message: {@noperm}

  trigger:
    if arg-1 is not set:
      send "{@noplayername}"
      stop

    if arg-2 is not set:
      add "[%now%] {@warn} &7by &f%player%&7: %arg-2%" to {history::%arg-1%::*}
      broadcast "{@warn} &c%player%&c &ffigyelmeztette &c%arg-1%&c &fjátékost!"
      stop

    broadcast "{@warn} &c%player%&c &ffigyelmeztette &c%arg-1%&c &fjátékost! Indok: &c%arg-2%"
    add "[%now%] {@warn} &7by &f%player%&7: %arg-2%" to {history::%arg-1%::*}

command /silentban [<player>] [<text>]:
  permission: modera.silentban
  permission message: {@noperm}

  trigger:
    if arg-1 is not set:
      send "{@noplayername}"
      stop

    if arg-2 is not set:
      execute player command "minecraft:ban %arg-1% &c%player%&c &fkitiltott téged!"
      stop

    execute console command "minecraft:ban %arg-1% &c%player%&c &fkitiltott téged! %newline% &fIndok:&f &c%arg-2%"

command /silentunban [<offline player>]:
  permission: modera.silentunban
  permission message: {@noperm}

  trigger:
    if arg-1 is not set:
      send "{@noplayername}"
      stop

    if arg-1 is banned:
      send "&aFeloldottad %arg-1% tiltását!"

    else:
      send "&cEz a játékos nincs kitiltva!"

command /history <offline player>:
    permission: modera.history
    permission message: {@noperm}
    trigger:
        if arg-1 is not set:
            send "{@noplayername}"
            stop

        if {history::%arg-1%::*} is not set:
            send "&e%arg-1% &7játékosnak nincsenek büntetési előzményei."
            stop

        send "&7&m================&r &c%arg-1% Előzményei &7&m================"
        
        loop {history::%arg-1%::*}:
            send "&7- %loop-value%"
            
        send "&7&m================================================"

command /clearhistory <offline player>:
    permission: modera.clearhistory
    permission message: {@noperm}
    trigger:
        if arg-1 is not set:
            send "{@noplayername}"
            stop

        clear {history::%arg-1%::*}
        send "&aSikeresen törölted &e%arg-1% &aösszes előzményét!"